import './style.css';
import './header.css';
import './preloader.css';
import './greeting.css';
import './bouquet.css';
import './timeline.css';
import './location.css';
import './dress-code.css';
import './rsvp.css';
import './final.css';
import './footer.css';
import './reveal.css';
import { initHeader } from './header';
import { initSoundToggle } from './audio';
import { initPreloader } from './preloader';
import { initLetter } from './letter';
import { initBouquet } from './bouquet';
import { initTimeline } from './timeline';
import { initLocation } from './location';
import { initRsvp } from './rsvp';
import { initFinal } from './final';
import { initReveals } from './reveal';

initHeader();
initSoundToggle();
initPreloader();
initLetter();
initBouquet();
initTimeline();
initLocation();
initRsvp();
initFinal();
initReveals();
